### ISSUE TITLE
[Angular 9] Compilation error after upgrading to v9

### ISSUE THREAD

**Issue by laneschmidt** [michaeldoye/mat-progress-buttons#64]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [] feature request
```

### OS and Version?
macOS Mojave 10.14.5

### Versions
- Angular: 9.0.0
- CDK/Material: 9.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Mojave 10.14.5
```
Angular CLI: 9.0.1
Node: 12.15.0
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

### Repro steps
Upgrade from v8 to v9.

### The log given by the failure
```
@project/app: ERROR in Failed to compile entry-point mat-progress-buttons (es2015 as esm2015) due to compilation errors:
@project/app: ../../node_modules/mat-progress-buttons/esm2015/mat-progress-buttons.js:181:26 - error NG1010: Value at position 1 in the NgModule.imports of MatProgressButtonsModule is not a reference: [object Object]
@project/app: 181                 imports: [
@project/app:                              ~
@project/app: 182                     CommonModule,
@project/app:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@project/app: ...
@iproject/app: 187                     MatIconModule
@project/app:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@project/app: 188                 ],
@project/app:     ~~~~~~~~~~~~~~~~~
```

### Desired functionality
Starting the project should work without compiler errors.

**Comment by AndreyBespamyatnov** [comment]
I have the same issue

**Comment by insomnia1337** [comment]
bump the same here

**Comment by lujakob** [comment]
@michaeldoye: I created a PR with the Angular 9 update. Would be happy if you could have a look as it's a blocker for several of my projects. Thanks :)

**Comment by michaeldoye** [comment]
Thank you to @lujakob! The new version is now available. Apologies for the delay, and thank you for the patience. <3
